// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {opportunities} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<main.LoginResponse>;

export function SearchOpportunities(arg1:string,arg2:string):Promise<opportunities.SearchResult>;
