// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllSettings() {
  return window['go']['main']['App']['GetAllSettings']();
}

export function GetCwd() {
  return window['go']['main']['App']['GetCwd']();
}

export function GetOpportunityNaicsCodes() {
  return window['go']['main']['App']['GetOpportunityNaicsCodes']();
}

export function GetOpportunityTypes() {
  return window['go']['main']['App']['GetOpportunityTypes']();
}

export function GetSystemStatus() {
  return window['go']['main']['App']['GetSystemStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function PullLatest() {
  return window['go']['main']['App']['PullLatest']();
}

export function SearchOpportunities(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchOpportunities'](arg1, arg2, arg3);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
